# This file was generated by GoReleaser. DO NOT EDIT.
cask "chough" do
  name "chough"
  desc "Fast ASR CLI using Parakeet TDT 0.6b V3"
  homepage "https://github.com/hyperpuncher/chough"
  version "0.2.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chough"
  depends_on formula: [
      "ffmpeg",
    ]

  on_macos do
    on_intel do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_darwin_x86_64.tar.gz"
      sha256 "8b67bab44d220774c794a76a0adf8dae4cc16cb8553f680bbd93e67ad92d8ea9"
    end
    on_arm do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_darwin_arm64.tar.gz"
      sha256 "9af4237cff9d8c5cea86abf2df8c3e8db75330485b83f68ff9482624fce1186e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_linux_x86_64.tar.gz"
      sha256 "5b994cd9a53f8106630caff52baf54ab3e01aec1305d38f3003d198d119c8ec3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
