# This file was generated by GoReleaser. DO NOT EDIT.
cask "chough" do
  name "chough"
  desc "Fast ASR CLI using Parakeet TDT 0.6b V3"
  homepage "https://github.com/hyperpuncher/chough"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chough"
  depends_on formula: [
      "ffmpeg",
    ]

  on_macos do
    on_intel do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_darwin_x86_64.tar.gz"
      sha256 "028215e8ec4120e9b4a273bf2716ea80bed0dbec5e8fe3ac24200ebc63a7a3e5"
    end
    on_arm do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_darwin_arm64.tar.gz"
      sha256 "216b1411916c93e2ba95d14dfecdadb511e605b2fc6d1acc52e8aa9916bb5b49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_linux_x86_64.tar.gz"
      sha256 "ace2baa7352af39f5b51b61a8a98dd8ce524a45628c6b48551be5ef606af8c81"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
