# This file was generated by GoReleaser. DO NOT EDIT.
cask "chough" do
  name "chough"
  desc "Fast ASR CLI using Parakeet TDT 0.6b V3"
  homepage "https://github.com/hyperpuncher/chough"
  version "0.1.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chough"
  depends_on formula: [
      "ffmpeg",
    ]

  on_macos do
    on_intel do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_darwin_x86_64.tar.gz"
      sha256 "002d3cf157c70decb759466f6eeadff95af26b78ad348143fa5e442d9c06153d"
    end
    on_arm do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_darwin_arm64.tar.gz"
      sha256 "7e6a852ed5a229d325d64e78846aa05008e325fb36b79b5a84b24bae6d95a196"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_linux_x86_64.tar.gz"
      sha256 "a43da39fbf73ffcd23edfe1e3b2a4019c6b252e71bb1018ea67697af4bc663b3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
